/*
 * dspi_msp432p401r.h
 *
 *  Created on: 1 May 2017
 *  Author: Chia Jiun Wei
 * <J.W.Chia@tudelft.nl>
 */

#ifndef INCLUDE_DSPI_MSP432P401R_H_
#define INCLUDE_DSPI_MSP432P401R_H_

#include <driverlib.h>

#define EUSCI_B0_PORT GPIO_PORT_P1                  //GPIO_PORT_P# and GPIO_PIN# can be found in gpio.h
#define EUSCI_B0_MISO GPIO_PIN7
#define EUSCI_B0_MOSI GPIO_PIN6
#define EUSCI_B0_CLK  GPIO_PIN5
#define EUSCI_B0_PINS (EUSCI_B0_MISO | EUSCI_B0_MOSI | EUSCI_B0_CLK)

#define EUSCI_B1_PORT GPIO_PORT_P6
#define EUSCI_B1_MISO GPIO_PIN5
#define EUSCI_B1_MOSI GPIO_PIN4
#define EUSCI_B1_CLK  GPIO_PIN3
#define EUSCI_B1_PINS (EUSCI_B1_MISO | EUSCI_B1_MISO | EUSCI_B1_CLK)

#define EUSCI_B2_PORT GPIO_PORT_P3
#define EUSCI_B2_MISO GPIO_PIN7
#define EUSCI_B2_MOSI GPIO_PIN6
#define EUSCI_B2_CLK  GPIO_PIN5
#define EUSCI_B2_PINS (EUSCI_B2_MISO | EUSCI_B2_MOSI | EUSCI_B2_CLK)

#define EUSCI_B3_PORT GPIO_PORT_P10
#define EUSCI_B3_MISO GPIO_PIN3
#define EUSCI_B3_MOSI GPIO_PIN2
#define EUSCI_B3_CLK  GPIO_PIN1
#define EUSCI_B3_PINS (EUSCI_B3_MISO | EUSCI_B3_MOSI | EUSCI_B3_CLK)

#define EUSCI_A0_PORT GPIO_PORT_P1                  //GPIO_PORT_P# and GPIO_PIN# can be found in gpio.h
#define EUSCI_A0_MISO GPIO_PIN2
#define EUSCI_A0_MOSI GPIO_PIN3
#define EUSCI_A0_CLK  GPIO_PIN1
#define EUSCI_A0_PINS (EUSCI_A0_MISO | EUSCI_A0_MOSI | EUSCI_A0_CLK)

#define EUSCI_A1_PORT GPIO_PORT_P2
#define EUSCI_A1_MISO GPIO_PIN2
#define EUSCI_A1_MOSI GPIO_PIN3
#define EUSCI_A1_CLK  GPIO_PIN1
#define EUSCI_A1_PINS (EUSCI_A1_MISO | EUSCI_A1_MISO | EUSCI_A1_CLK)

#define EUSCI_A2_PORT GPIO_PORT_P3
#define EUSCI_A2_MISO GPIO_PIN2
#define EUSCI_A2_MOSI GPIO_PIN3
#define EUSCI_A2_CLK  GPIO_PIN1
#define EUSCI_A2_PINS (EUSCI_A2_MISO | EUSCI_A2_MOSI | EUSCI_A2_CLK)

#define EUSCI_A3_PORT GPIO_PORT_P9
#define EUSCI_A3_MISO GPIO_PIN6
#define EUSCI_A3_MOSI GPIO_PIN7
#define EUSCI_A3_CLK  GPIO_PIN5
#define EUSCI_A3_PINS (EUSCI_A3_MISO | EUSCI_A3_MOSI | EUSCI_A3_CLK)

#endif /* INCLUDE_DSPI_MSP432P401R_H_ */
